### ISSUE TITLE
--shell-type readline doesn't work

### ISSUE THREAD

**Issue by asmeurer** [scopatz/xonsh#1072]
If I start xonsh with `--shell-type readline`, it still uses prompt_toolkit. I have to uninstall prompt_toolkit to make it use readline.

**Comment by adqm** [comment]
Confirmed.  It looks like the value that comes in from the command line arguments is being overridden by the value in the `.xonshrc`.

**Comment by adqm** [comment]
This might make a good first patch for someone.  The issue is with [line 47 of `xonsh/shell.py`](https://github.com/scopatz/xonsh/blob/master/xonsh/shell.py#L47), which totally ignores the value of `shell_type` that was passed in (from the command line arguments).

What we should really do is first check the `shell_type` that was passed in, and only check the value from the environment if that is `None`

**Comment by adqm** [comment]
Fixed in #1100; thanks @VHarisop!  @asmeurer, feel free to re-open if this doesn't work for you.
