### ISSUE TITLE
CLI-commands cannot deal with preceeding whitespace

### ISSUE THREAD

**Issue by SmartViking** [scopatz/xonsh#110]
```
uglemat@uglemat ~/Public/xonsh/xonsh master $      ls
............................................. 
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 137, in push
    locs=self.ctx)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 84, in compile
    tree = self.parse(input, ctx, mode=mode)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 62, in parse
    tree = self._parse_ctx_free(input, mode=mode)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 118, in _parse_ctx_free
    mode=mode, debug_level=self.debug_level)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/parser.py", line 271, in parse
    debug=debug_level)
  File "/usr/lib/python3/dist-packages/ply/yacc.py", line 269, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/usr/lib/python3/dist-packages/ply/yacc.py", line 1051, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/parser.py", line 2119, in p_error
    column=self.lexer.token_col(p)))
  File "/usr/local/lib/python3.4/dist-packages/xonsh/parser.py", line 341, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:3: ('code:      ',)
uglemat@uglemat ~/Public/xonsh/xonsh master $ 
```

Maybe this can be fixed by putting a str.lstrip in the right place? Should `$[  ls]` work, in that case?

**Comment by scopatz** [comment]
I actually don't think that they should be able to deal with this. I'll explain more after work.

**Comment by scopatz** [comment]
Hi @SmartViking! Sorry for not getting this yesterday.  Basically, here is the situation. In Python mode, we have a situation that is:

* whitespace insensitive inside of an expression
* has blocks defined by initial indentation level

Meanwhile in subprocess mode we have a situation that is:

* whitespace sensitive inside of expressions
* does not allow blocks

and in Bash:

* whitespace sensitive inside of expressions
* has blocks with delimiters (if-fi, for-end, etc)
* initial whitespace is ignored.

So to be super explicit about it, Bash and Python have complementary whitespace and blocking rules. Subprocess mode has to resolve these, which it does through some lexer tricks and by limiting the bad behaviour of Bash.  

I think that ignoring whitespace at the beginning of a subproc expr would add significant ambiguity to the language. I think the pain would not be worth the gain.  Let's look at a couple of examples.  The following seems like resonable xonsh codes. 

```python
if True:
    print("WoW")
    ls -l
    print("MoM")
```

This could also be OK:

```python
if True:
    print("WoW")
    $[ls -l]
    print("MoM")
```

This seems a little weird, but maybe acceptable:

```python
if True:
    print("WoW")
    $[          ls -l]
    print("MoM")
```

But if we would truly allow leading whitespace insensitive subproc mode, then this has to apply even when the uncaptured process operator is absent.

```python
if True:
    print("WoW")
              ls -l
    print("MoM")

if True:
    print("WoW")
ls -l
    print("MoM")
```

Both of these look deeply wrong to me.  Folks have lived with (and liked) Python's whitespace indention.  Since xonsh *is* Python - with some Bashisms - I think it makes sense to keep Python's rules over Bash's.  

That said, if the subproc indentation thing is super annoying to actually deal with, we could always `lstrip()` just the first line of the prompt (ie not the subsequent lines in a multiline prompt).  However, this would be a feature of the Shell, and not a feature of the xonsh language. I'd likely accept a PR to that effect if it kept people using xonsh :). 

I hope all of that makes sense.

**Comment by SmartViking** [comment]
That does make sense. My feeling is that trying out commands with preceding whitespace will easily happen, you know when people paste lines of codes into the shell and such, and users might be a little surprised by this behavior. Your Shell solution seems apt.

**Comment by SmartViking** [comment]
Looking at the code for `cmd.Cmd`, it becomes apparent that you can't write 'EOF':

```
$ xonsh                                                                                         {~}
uglemat@uglemat ~ $ EOF = "Hello"
uglemat@uglemat ~ $ EOF
'Hello'
uglemat@uglemat ~ $ 
uglemat@uglemat ~ $ 'Hello'
uglemat@uglemat ~ $ 'Hello'
uglemat@uglemat ~ $ pkill xonsh
zsh: terminated  xonsh
$ xonsh                                                                                     {~|143}
uglemat@uglemat ~ $ EOF

$  
```
In the first example, I couldn't exit with Ctrl-D, so I had to use `pkill`. I'm not completely sure how the behavior above arises but I think this would be difficult to fix.

**Comment by scopatz** [comment]
Hi @SmartViking! Yes, so EOF is an alias to the `xonsh.aliases.exit()` function.  Ctrl-D simply writes EOF.  If you happen to overwite this alias accidentally, you can still use the `exit` and `quit` aliases to leave xonsh.

**Comment by SmartViking** [comment]
That makes sense. It just seems kind of inelegant of `cmd.Cmd` to do that. But it's hardly worth the time and effort to fix that.
