### ISSUE TITLE
dir, set, slash

### ISSUE THREAD

**Issue by klonuo** [scopatz/xonsh#1124]
So I'm on Windows, and thought to try xonsh, as any helper compared to bare Windows console is godsend

```shell
klonuo@home ~ $ dir
<function dir>
klonuo@home ~ $ dir /p
NameError: name 'p' is not defined
klonuo@home ~ $ set
set
klonuo@home ~ $ set p
xonsh: subprocess mode: command not found: set
Did you mean one of the following?
    ren:  Alias
    del:  Alias
klonuo@home ~ $ echo klo
xonsh: subprocess mode: command not found: echo
```

`dir` should list folder, like `ls` on *nix. I know that `dir` is Python keyword, but this is shell application and listing a folder should work.

`dir /p` should list files paged, but it seems that no command can be executed with slash as argument prefix, and guess that all Windows commands have arguments which a prefixed with slash (just like `-` or `--` on *nix)

`set` is pandan for `export` on *nix, and it is great Python keyword. Further `set p` should list all environment variables that start on "p".

`echo` cant be found?

I guess there are other issues as I just tried this app as mentioned, but although it can run on Windows, it does not seem like it provides friendlier environment.

ps. I was surprised that `type` (*nix `cat`) works. go figure ;)

**Comment by klonuo** [comment]
As a comment, reproducible crash:

```pytb
C:\temp>echo klo > test.txt

C:\temp>xonsh
klonuo@home C:\temp $ del "test.txt"
Traceback (most recent call last):
  File "C:\Python35\Scripts\xonsh-script.py", line 9, in <module>
    load_entry_point('xonsh==0.3.2', 'console_scripts', 'xonsh')()
  File "c:\python35\lib\site-packages\xonsh\main.py", line 254, in main
    shell.cmdloop()
  File "c:\python35\lib\site-packages\xonsh\ptk\shell.py", line 115, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "c:\python35\lib\site-packages\xonsh\ptk\shell.py", line 84, in singleline
    line = self.prompter.prompt(**prompt_args)
  File "c:\python35\lib\site-packages\xonsh\ptk\shortcuts.py", line 109, in prompt
    document = cli.run(reset_current_buffer=False)
  File "c:\python35\lib\site-packages\prompt_toolkit\interface.py", line 387, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "c:\python35\lib\site-packages\prompt_toolkit\eventloop\win32.py", line 78, in run
    callbacks.feed_key(k)
  File "c:\python35\lib\site-packages\prompt_toolkit\interface.py", line 916, in feed_key
    self._active_cli.input_processor.feed_key(key_press)
  File "c:\python35\lib\site-packages\prompt_toolkit\key_binding\input_processor.py", line 174, in feed_key
    self._process_coroutine.send(key_press)
  File "c:\python35\lib\site-packages\prompt_toolkit\key_binding\input_processor.py", line 146, in _process
    self._call_handler(matches[-1], key_sequence=buffer)
  File "c:\python35\lib\site-packages\prompt_toolkit\key_binding\input_processor.py", line 190, in _call_handler
    handler.call(event)
  File "c:\python35\lib\site-packages\prompt_toolkit\key_binding\registry.py", line 32, in call
    return self.handler(event)
  File "c:\python35\lib\site-packages\xonsh\ptk\key_bindings.py", line 132, in multiline_carriage_return
    carriage_return(b, event.cli)
  File "c:\python35\lib\site-packages\xonsh\ptk\key_bindings.py", line 55, in carriage_return
    elif not current_line_blank and not can_compile(b.document.text):
  File "c:\python35\lib\site-packages\xonsh\ptk\key_bindings.py", line 102, in can_compile
    locs=builtins.__xonsh_ctx__)
  File "c:\python35\lib\site-packages\xonsh\execer.py", line 99, in compile
    code = compile(tree, filename, mode)
ValueError: expression which can't be assigned to in Del context
```

**Comment by adqm** [comment]
Thanks for bringing this up, @klonuo.

The hard thing about all of these examples is that they overlap in name with Python built-ins.  The trade-off that has been made throughout xonsh is that, if there is an ambiguity, Python always wins over shell commands.

So the `dir /p` example is trying to take Python's built-in `dir` function and divide it by a variable `p`.  And the `del "filename"` example is trying to delete the Python object represented by the constant string you gave it.  Similarly, `set` is referring to the Python built-in (though I agree it is a bug that this destroys xonsh instead of just erroring).

Unfortunately, xonsh will not have one-to-one compatibility with the Windows command line.  But there are ways to do all of these things.

The most straightforward thing to do would be to wrap these commands in `![]`, which will force them to be run as subprocess commands.  I know that's a little bit tedious, but this should make some of these things work (the `del` and `dir` examples, at least; e.g., `![dir /p]`).

The `set` example still doesn't work, possibly because `set` is a `cmd.exe` built-in and not an executable on the path?  For creating environment variables (or referencing their values) you can use Pythonic syntax, but wusing a name starting with `$`.  For example, `$MY_NEW_ENV_VAR = 'hello'`, or `print($HOMEDRIVE)`.

There is also the built-in `__xonsh_env__`, which is a mapping from environment variable names to their values.  So to get all of the env vars that start with 'p', for example, one could do: `[i for i in __xonsh_env__ if i.lower().startswith('p')]`.  Of course, that's a little bit tedious to type, but it would be possible to make a xonsh alias that would do that same thing and make it easier to type.

**Comment by adqm** [comment]
Adding the label "prompt_toolkit" since the `del` issue only happens when running the ptk shell.

**Comment by adqm** [comment]
Also, maybe one of our Windows folks (@melund, @BYK) might have some more insight here?

**Comment by klonuo** [comment]
@adqm, thanks for your comments and for `![]` tip

**Comment by scopatz** [comment]
Hi @klonuo - thanks for bringing this up!  I agree with @adqm 100% here.  We take the stance that "Python always wins" and the cases that you bring up are mostly ambiguous between Python and subprocess mode.

However, as @adqm says, you can always wrap a subprocess command in `![]` or `$[]` to make it non-ambiguous.

I'd also like to add that if you are getting super annoyed at Python builtins superceding Windows commands, you can always do something like the following in your xonshrc:

```python
import builtins
builtins.pydir = builtins.dir  # rename dir
del builtins.dir  # remove old dir
```

Of course, there is no telling what this could mess up and we can't ship xonsh this way, but if it works for you, great!

**Comment by scopatz** [comment]
Also, try this in a terminal session first so that you don't end up with a xonshrc that totally kills your system.

**Comment by klonuo** [comment]
Ok, thanks again for your quick replies with tips.

As it is `![]` is nice workaround. Wanted to ask just one question, can `![]` be simplified to bang (without brackets, like in IPython)?

**Comment by adqm** [comment]
> As it is ![] is nice workaround. Wanted to ask just one question, can ![] be simplified to bang (without brackets, like in IPython)?

You can come pretty close with the following (untested, but I think it should work):
`aliases['!'] = lambda args, stdin=None: ![@(args)]`

The only difference is that this requires a space between the `!` and the command

**Comment by scopatz** [comment]
> As it is ![] is nice workaround. Wanted to ask just one question, can ![] be simplified to bang (without brackets, like in IPython)?

No, not currently.  Even though they connote the same idea, IPython's `!` will eat the rest of the line, making it more of a statement than an expression.  Xonsh uses `![...]` so you can easily place a subprocess anywhere.  

I would be a little opposed to the idea of adding IPython's `!` since it would be duplicated syntax.  Also, the idea with xonsh is that you don't normally need to write `![]` yourself.

Also @adqm's solution is brilliant , as always :)

**Comment by klonuo** [comment]
Excellent support!

Thanks for all your time.
Closing.

**Comment by klonuo** [comment]
oops, perhaps I shouldn't have done this as it's tagged with prompt toolkit label

**Comment by adqm** [comment]
Yes, just as a reminder that there still is that one bug.  Actually, maybe better to close this and we can make a new issue specifically for the ptk issue, since this had a lot of other discussion.
