### ISSUE TITLE
Add bash-like history syntax (!!, !n, etc.)

### ISSUE THREAD

**Issue by bsmt** [scopatz/xonsh#153]
[Here's](http://www.softpanorama.info/Scripting/Shellorama/bash_command_history_reuse.shtml) a decent (albeit ugly) description of what bash can do. I'm not sure if duplicating all of that is necessary, should probably have !!, !n, and !-n at the very least. I've already started working on this, but it'll probably take me a while to get familiar with all of the code.

**Comment by scopatz** [comment]
Hi @bsmt - thanks for reporting this issue.  I agree that this functionality should exist, in some form.  It is probably dependent on #17 to some extent.  

That said, I feel like copying the `!`, `!!`, etc  syntax here is a mistake.  This is a bit of arcana that makes bash especially hard to use.  I'd much prefer a built-in alias to do the same thing.  Pull requests very welcome here.

**Comment by bsmt** [comment]
I guess I could start by just implementing stuff on the parser end until #17 is done. What do you think we should use instead of the ! stuff?

**Comment by scopatz** [comment]
My point is that this shouldn't touch the parser at all.  history lookup and execution should not be part of the language syntax, but rather but rather be a built-in function.  You could try connecting with @anula, or you could implement a really simple history list for the time being.

**Comment by bsmt** [comment]
Ah. Would that still work within a subprocess command (say, like sudo !! in bash/zsh)? I just started using xonsh a day or two ago so I'm not totally sure how everything works. Even if it doesn't, I guess there could just be a built-in alias to run the last command in sudo; that's probably what 90% of people use this feature for anyways.

**Comment by scopatz** [comment]
Ahh so for that kind of thing, you'd drop into python mode, go to the history object (call it `hist`) and then get the last stdin.  For example:

```console
$ sudo @(hist[-1].stdin)
```

Or something similar.  We could always add more direct access mechanisms too, but that is the basic idea.

**Comment by bsmt** [comment]
Gotcha; that makes sense. I guess this issue is somewhat redundant then.

**Comment by scopatz** [comment]
Well, this isn't entirely redundant in the sense that `$ !!` will execute the command, and `$ @(hist[-1].stdin)` might just print the command list, depending on how the history class is implemented.  So there is room for an alias that executes commands from history.

**Comment by scopatz** [comment]
It just wouldn't apply in the `sudo`, `time`, etc case.

**Comment by wrywerytwreywery** [comment]
fwiw, I think the example from above of `sudo @(hist[-1].stdin)` wouldn't quite work without some modification to xonsh, because the `@(...)` doesn't currently parse out whatever is inside of it; it just returns it verbatim as a single piece of the command to be run.  So, for example:

`@("ls") -la` would work (the result of the Python-mode chunk, `"ls"`, is a valid command), but...

```
$ @("ls -la")
xonsh: subprocess mode: command not found: ls -la
```
because what comes out is interpreted as a _single chunk_ rather than as two pieces of a command.

But also, it should be able to alias that piece (once we figure out how it works) so that you could do something like the following:
```
def sudolast(args, stdin):
    $[sudo @(hist[-1].stdin)]
aliases["sudolast"] = sudolast
```

**Comment by scopatz** [comment]
Yep.  The hooks are there to do this, it just needs to be implemented.

**Comment by SmartViking** [comment]
The problem above is kind of like when you construct lists in lisp:

```scheme
scheme@(guile-user)> (define cmd '(ls -al))
scheme@(guile-user)> `(sudo ,cmd)
$6 = (sudo (ls -al))
scheme@(guile-user)> `(sudo ,@cmd)
$7 = (sudo ls -al)
scheme@(guile-user)> 
```

Maybe there should be an analog to `,@` for xonsh?

**Comment by scopatz** [comment]
@SmartViking what does `,@` do in lisp?  It has been over a decade so a refresher would be nice. :) It looks like it expand at the scope of the `,@` rather than inserting at the scope of `,`.

**Comment by wrywerytwreywery** [comment]
It seems like what we want is _almost_ `*@("ls -la")` (assuming the changes to "star" from [PEP 448](https://www.python.org/dev/peps/pep-0448/)), except that `@(...)` makes a string, so that expansion wouldn't quite work, I think.  Of course, that is workable since the definition of `@(...)` isn't set in stone.  

My proposal would be: 
* `@()` works as before, returning a string that is added to the subprocess command.
* `*@()` evaluates its contents to a string as `@()` does, but returns a list (parsed with `shlex`?) of strings, each of which is added to the subprocess command.

**Comment by scopatz** [comment]
So my proposal is to not add any extra syntax, but rather to update the parses such that:

* if `@()` returns a string, its inserted as the next argument in a subrporcess.
* else if `@()` returns a list or other `collections.Sequence`, it is assumed that this is a list of string and they extend the argument list, much like the backtick regex
* else call `str()` on the result of `@()` and append it to the argument list.

**Comment by ankostis** [comment]
For those landed here, some bash history-expansions (`!!, !$, !*, !^`) supported with `xontrib load bashisms` .
