### ISSUE TITLE
!! alias

### ISSUE THREAD

**Issue by aig787** [scopatz/xonsh#205]
Would it be possible to add !! as an alias to the last executed command like in bash? I tried to add it, but it looks like it gets hung up on the parsing stage. Probably because `!` is valid python input? I'm not really sure where to start implementing that.

**Comment by scopatz** [comment]
This came up in #153 as well. I personally don't really like the syntax, but if people are clamouring for it, it is hard to say no.  However, before doing this, we first need a robust history object, see #17.  I would be overjoyed if you implement this @aig787 :).  Other people have said that they would try, but i haven't seen a PR yet, so I think it is OK to go ahead and do it.

**Comment by aig787** [comment]
I'm not particularly attached to the syntax of it, the benefit I see there is that it's easier for newcomers. It would be just as easy to suggest an alternate command if someone typed `!!` and they could alias it if they like. I'd be happy to jump into a history object and see where things go from there, but I'm out of my depth when things get down to the parsing level. To change that stuff I would probably need some guidance.

**Comment by scopatz** [comment]
> I'd be happy to jump into a history object and see where things go from there,

Awesome!  That is definitely a PR on its own.

> but I'm out of my depth when things get down to the parsing level. To change that stuff I would probably need some guidance.

No worries.  I am glad to help, and I am sure @wrywerytwreywery is too.  The more people who know more of the code base the better.  It'd be great to bring you up to speed on that part when the time comes.

**Comment by aig787** [comment]
So, IPython has its history in a SQLite database. There's some flexibility and speed that comes with that, but then we don't have the advantage of having it in an easily accessible text file. Any preference/thoughts on which way to go with that?

**Comment by scopatz** [comment]
I vastly prefer JSON for this.

**Comment by aig787** [comment]
I tend to agree. That's the direction I'll head down then.

**Comment by scopatz** [comment]
Great!

**Comment by wrywerytwreywery** [comment]
This sounds very nice.  I think what you all are saying is the right approach: make a rich history object of some kind, and then alias `!!` to some operation on it, rather than introducing `!!` as a new built-in feature itself.

It was actually surprising to me that aliasing something to `!!` (for example, `aliases['!!'] = lambda x,stdin=None: x`) doesn't work.  I think I can see why, though, now; and I think the solution is going to require some thinking on our part.  In particular, the question that comes to mind is: what should be a valid name in subprocess mode?  If we want to allow aliases like `!!`, then one fix would be to allow names in subprocess mode that aren't allowed in Python mode.  This might get complicated from the lexer's perspective, but I think it shouldn't be too bad if we think it through.

Once we decide on something, I would be happy to take a stab at it, or I would be happy to help if you want to try to tackle it, @aig787 .

**Comment by wrywerytwreywery** [comment]
Also, maybe going down the lines of premature optimization, but I think it would also be nice to be able to turn that "rich history" on and off, and, ideally to turn pieces of it (e.g., storing the resulting stdout) on/off as well, independently of the others.

Also also, @anula and @bsmt had expressed some interest in working on history as well (in #17).  I'm not sure where things stand with that, but if they have made some progress, it might be worth trying to coordinate.

**Comment by scopatz** [comment]
> It was actually surprising to me that aliasing something to !! (for example, aliases['!!'] = lambda x,stdin=None: x) doesn't work.

I was also surprised by that.  Probably warrants further investigation.

**Comment by scopatz** [comment]
that is, I have been meaning to look into it :)

**Comment by wrywerytwreywery** [comment]
It seems like it is happening because `!` is coming out as an `ERRORTOKEN`, which makes sense in Python mode.

This feels kind of wrong, but I think in subprocess mode, we might want to turn that into a `NAME` (possibly along with all other `ERRORTOKEN`s that don't have some other meaning?), or maybe some other new kind of token to distinguish that it can be considered a name only in subprocess mode.

**Comment by scopatz** [comment]
I think that is the right thing to do.  That was the intent in the original tokenizer, even though I think this case broke that one too.

**Comment by aig787** [comment]
I have what I think is a good design for how the history should work, I think the next step is to implement a `history` command so I can do some more testing while I try to replace readline with it. Currently the history is referenced in the shell.py with `self.history` and I'm not sure how to reference that from within aliases.py. Any suggestions on how to go about that?

**Comment by scopatz** [comment]
Hi @aig787 - I think that you should move all of the core history functionality to aliases.py or its own module (hist.py?) and then simply reference it from the shell.  Does that make sense?

**Comment by aig787** [comment]
@scopatz Yes that makes sense, how would I make sure both the shell and aliases are referencing the same instance of the history object though?If I load the module in each separately it'll be empty. Would it make sense to add that as a builtin property like `xonsh.history`?

**Comment by scopatz** [comment]
Yes, you could add a `history` variable as an attribute to builtins.  See the `load_builtins()` and `unload_builins()` functions in the `built_ins.py` file (I think)

**Comment by anula** [comment]
You are definitely more advanced in implementing history than I am (not putting as much time into it as I wanted), so good luck with that. But if you need a hand (or two) in implementing something I still would be willing to help.

**Comment by scopatz** [comment]
This was implemented

**Comment by ankostis** [comment]
For those landed here, bash history-expansions with `xontrib load bashisms` .
