### ISSUE TITLE
xonsh as default shell; ssh issues

### ISSUE THREAD

**Issue by mankoff** [scopatz/xonsh#257]
I set xonsh as my default shell. I can ssh in to my machine from itself (`ssh localhost`) but my iPad can no longer connect to my machine. This a bit hard to debug. The log on the iPad says authentication successful but then something stops it from working.

Is there a way to set only local user interactive terminal sessions as `xonsh`?

**Comment by wrywerytwreywery** [comment]
Thanks for reporting, @mankoff!

Unfortunately, I am not able to reproduce this (I regularly ssh into several machines of mine that run xonsh as their default shells).  I also don't own an iPad, so I am not sure I will be able to test this any further.  Can you provide any information about the machines you are trying to SSH to/from?  Some things that might be helpful:
  * Is there a particular app you are using for SSH?  If so, have you tried using another?
  * How did you install xonsh on the machine you are trying to connect to (pip, conda, install from master, etc)?

> Is there a way to set only local user interactive terminal sessions as xonsh?

As far as I know, there isn't.  As a temporary workaround, it might do to leave bash as your default, and to add something like the following to your .bashrc:

```
if [ -z "$XONSH_STARTED" ] && [ -z "$SSH_CLIENT" ] && [ -z "$SSH_TTY" ]; then
    export XONSH_STARTED=true;
    xonsh;
fi
```

I haven't tested this snippet extensively, but it tries to start xonsh if you are not connecting via ssh (the extra check for whether xonsh has been started is to avoid an infinite loop, since xonsh itself calls bash during startup).

**Comment by wrywerytwreywery** [comment]
As another test, can you also try running a single command on your other machine (with xonsh as default) via SSH from the iPad?  e.g.: 
`$ ssh remote_host echo "hello"`

**Comment by mankoff** [comment]
I found the culprit. I had an accented character in my .xonshrc. Even in a comment, `foö` crashes it on login using iTerm.app on the iPad.

**Comment by scopatz** [comment]
Sounds like a unicode issue.
