### ISSUE TITLE
Use readline init file 

### ISSUE THREAD

**Issue by scopatz** [scopatz/xonsh#290]
https://cnswww.cns.cwru.edu/php/chet/readline/readline.html#SEC32

https://cnswww.cns.cwru.edu/php/chet/readline/readline.html#SEC9

**Comment by asmeurer** [comment]
Specifically

```
Function: int rl_read_init_file (const char *filename)
Read keybindings and variable assignments from filename (see section 1.3 Readline Init File).
```

The standard library readline has `read_init_file` (for some reason, I thought you had to use pyreadline for this, but it looks like it's in the standard library). I'm not sure if it's the same, since it says, "Parse a readline initialization file. The default filename is the last filename used." (the last sentence is confusing to me; does it read ~/.inputrc by default or do you have to write that logic yourself?).

**Comment by asmeurer** [comment]
I looked at the CPython source for readline.c and now I'm even more confused. I looks like maybe the .inputrc reading happens in rl_initialize, which should be called automatically whenever readline is used. Are you doing something in xonsh that would disable that, or am I misunderstanding how this works?

**Comment by asmeurer** [comment]
I think I see now. I'm pretty sure it *does* read my inputrc, but the problem is that the xonsh setup_readline overrides some of my settings. I'm not entirely sure about some of them (e.g., I have `set completion-ignore-case on` but the tab completion in xonsh is still case sensitive, but I don't see that being set anywhere). 

It would help to separate out the custom readline stuff so that it can be disabled in .xonshrc (it would also help if everything that is done were documented). 

Secondary thought: I would try to pull out and reuse what IPython uses if possible (or just depend on IPython and import it). They seem to have this all worked out. 

Now I'll stop bugging you here now unless I decide to write some actual code.

**Comment by scopatz** [comment]
Hi @asmeurer - after a fair amount of digging, I realized that 

1. We set up readline in the same way as IPython,
2. None of our extra options impact the ignore casing option at all, and
3. IPython [implements ignore-case on its own!](https://github.com/ipython/ipython/blob/e51e50d36f2d05061ef7bdcea56531f5fca08f4c/IPython/core/completer.py#L1097)

So, I can go ahead and implement this idea in xonsh too, if you'd like. But as you say, it is not because the inputrc is not being read.

**Comment by asmeurer** [comment]
Hmm, I could have sworn that my other .inputrc modifications like https://github.com/asmeurer/dotfiles/blob/02c06f872e124fc912e0a6c005dbe1f8c7a2f7f7/.inputrc#L11 didn't work, but they seem to now. Maybe there's something different between my personal laptop and my work laptop. 

+1 for implementing ignore-case. Case sensitive tab completion is a stupid invention.

**Comment by scopatz** [comment]
Cool. I'll get on this then.
