### ISSUE TITLE
Add dirname, etc to FORMATTER_DICT

### ISSUE THREAD

**Issue by scopatz** [scopatz/xonsh#293]
Would be nice .

**Comment by scopatz** [comment]
Hey @asmeurer - what did you mean by this exactly.  They way Python string formatting works seems to forbid the calling of functions in the formatter.  The following could not work

```python
'{dirname({x})}'.format(dirname=os.path.dirname, x='/yo/mama')
```

The following could be made to work, but it is a little weird:

```python
'{dirname[{x}]}'.format(dirname=os.path.dirname, x='/yo/mama')
```

**Comment by asmeurer** [comment]
I think I just wanted a special variable for `basename(getcwd())` so I don't have to write https://github.com/asmeurer/dotfiles/blob/13f21dbbb8ae87dc7b2f544f53a8cf957c5f2639/.xonshrc#L18 (which incidentally I would keep anyway because of the "current working directory not found" bit, but maybe xonsh could do something there as well). It seems useful. In bash it's `\W`, which is a pretty common variable for PS1s.

Also, in bash, `\W` is `~` is the cwd is $HOME.

**Comment by asmeurer** [comment]
"dirname" probably came from me misremembering the dozens of os.path functions btw.

**Comment by scopatz** [comment]
Ok - that is very doable.
