### ISSUE TITLE
Virtual Terminal Prompt Issues

### ISSUE THREAD

**Issue by wrywerytwreywery** [scopatz/xonsh#34]
Running with xonsh as my shell (set via `chsh` rather than starting from within bash), some virtual terminals seem to have trouble with the `PROMPT` environment variable being a Python function rather than a string, leading it to display, e.g., the following as its prompt:

`<function default_prompt at 0x7f5ffba65400>`

Tested with lxterminal, terminator, and gnome-terminal on Ubuntu 14.04 64-bit.

**Comment by scopatz** [comment]
This is definitely a bug. I am going to have to look at this and your fix when I am more awake tomorrow.  Note that you can get the same behaviour by running xonsh from within bash from within xonsh.  This is because of the way the Env.detype() stores the variable. We might be able to do something fancier like de/persist the bytecode of callables... but I'd need to be less sleepy.

**Comment by scopatz** [comment]
Closed by #42
