### ISSUE TITLE
Problems with white spaces in file names

### ISSUE THREAD

**Issue by melund** [scopatz/xonsh#365]
There are some issues with whitespaces in file names on windows.

The worst one has appeared since the `_normpath()` was fixed to not remove the trailing slash or backslash from directories: 

```
$ cd 'my folder\' 
cd takes 0 or 1 arguments, not 2
```
The trailing backslash eats the quote since `cd 'my folder/'` works fine. 

Another is issue is auto completion:
```
$cd 'my <tab>
```
(notice the white space after `'my `)
This will start a new autcompletion. Thus:
`cd 'my 'my folder\'`

**Comment by scopatz** [comment]
First off, I agree that there are a lot of kinks to be worked out for whitespaces in filenames. I don't think that this is a Windows only issue, but it does hit Windows more often due to the backslashes.  

For the first example, though, you should be able to do `\\` to fix the issue, in the short term.

**Comment by melund** [comment]
This has also mostly been adressed
