### ISSUE TITLE
Problems using sudo with autocomplete

### ISSUE THREAD

**Issue by gforsyth** [scopatz/xonsh#421]
I'm stumped.  `sudo` is not playing nice with xonsh.  

I'm using Arch Linux and xonsh v0.2.2 with prompt_toolkit.

Completions work just fine unless I start the line with sudo and then I have no completion support.  I've also noticed that while `!!` will run the previous command, as expected, `sudo !!` returns 

```Bash
sudo: !!: command not found
```

`sudo env` shows that the sudo `SHELL` is set to `xonsh`

*EDIT:
to clarify, if I type `sudo` and then hit TAB it will open up the prompt_toolkit completion list, but shows only the files and folders in that directory.  If I start typing the name of a binary (say, `pacman`) there is no completion.

**Comment by scopatz** [comment]
Thanks for reporting @gforsyth. There are a few different issues here.

The first is that xonsh only does alias expansion on the first token. Since sudo is the first token, it is not expanding !!, which is an alias and not part of xonsh syntax. A simple sudo alias function that does alias expansion would fix this and probably should be in xonsh itself. Pull requests very welcome here.

The second issue is less clear where it is coming from. But xonsh relies on Bash completions. I don't know where sudo bash completions are defined, but it is a fair bet that that location is not present in the `$BASH_COMPLETIONS` variable. That is probably the right place to start looking.

**Comment by drufat** [comment]
I am facing a similar issue. Some autocompletions that work under bash, do not work under xonsh. For example trying the following at the bash command prompt under archlinux with the auto-complete package installed

    $ which gre[TAB]
    grep       gresource 

results in helpful completion tips. Doing the same in xonsh, results in no output. I am not sure what I need to do in xonsh to get the same behavior as in bash.

**Comment by scopatz** [comment]
Hi @drufat, can you check that the files listed in `$BASH_COMPLETIONS` actually exist. If not, we may need to do something different for arch.

**Comment by gforsyth** [comment]
@drufat @scopatz 

arch does use a different setup for completions -- they live in 
`/usr/share/bash-completion/bash_completion` but the attribute completions directory is the same, that is, `/usr/share/bash-completion/completions/git` is valid. 

I also found a bug in the prompt_toolkit_completer that prevented attributes from tab completing for, say, git.  Still trying to iron out a few kinks so that it works as expected, but I'll PR that soon.

**Comment by scopatz** [comment]
Ahh OK.  If you want to put it a PR for Arch fix that would be great.  Probably should add an `ON_ARCH` variable to tools.py

> I also found a bug in the prompt_toolkit_completer that prevented attributes from tab completing for, say, git. Still trying to iron out a few kinks so that it works as expected, but I'll PR that soon.

Looking forward to it!

**Comment by scopatz** [comment]
Thanks @gforsyth!
