### ISSUE TITLE
[Question] Making prompt_toolkit completion display configurable.

### ISSUE THREAD

**Issue by mdraw** [scopatz/xonsh#440]
Like I mentioned earlier in https://github.com/scopatz/xonsh/pull/436#issuecomment-151298879, I wanted to make the prompt_toolkit's completions configurable.
There are some design decisions that I think should better be discussed here before I create a PR, namely I really don't know how to name the needed environment variable and its possible values.

Some (bad?) ideas to give an example of what I mean:

- COMPLETIONS would be probably be confusing, given that there is already an independent BASH_COMPLETIONS variable.
- DISPLAY_COMPLETIONS (also too vague maybe)
- PTK_COMPLETIONS (which would use this prefix that you were not particularly fond of, @scopatz)

Some examples for possible value names:

- "No completions": False, None, 'false', none', 'off'
- "Single column": True, 'true', 'single', 'single_column'
- "Multiple columns": True, 'true', 'multi', 'multi_column'

(If True/'true' got used, we would have to decide if it means multi or single column.)

**Comment by scopatz** [comment]
Thanks for opening this issue @mdraw. Why not have a single variable called `$COMPLETIONS_DISPLAY`, and the value is a string which only may from the following set of option: `{'none', 'single', 'multi'}`. Or something similar.  If you wrote a custom ensurer function, you could automatically turn `True`, `False`, `None`, and any other values (like with different casings or yes/no) into the appropriate selection from this set.  That would be how I would do it.

I'm not sure that there is a *great* variable name here, but maybe @jonathanslenders has some suggestions, since he is the one who implemented all of this in ptk :)

**Comment by mdraw** [comment]
PR at https://github.com/scopatz/xonsh/pull/461

**Comment by scopatz** [comment]
#461 was merged, closing this.
