### ISSUE TITLE
Activating conda envinoments

### ISSUE THREAD

**Issue by tritemio** [scopatz/xonsh#488]
On Windows in cmd.exe, Miniconda3 and python 3.4 I start xonsh, activate a python 2 enviroment. After that, running python starts python 3.4 (the root environment python) instead of python 2:

```
>xonsh
temp@laser2002j-PC C:\Data\Antonio\software\src\voltagesensing master $ activate py2
Activating environment "C:\Users\laser2002j\Miniconda3\envs\py2"...
temp@laser2002j-PC C:\Data\Antonio\software\src\voltagesensing master $ python
Python 3.4.3 |Continuum Analytics, Inc.| (default, Nov  7 2015, 13:21:48) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by gforsyth** [comment]
Hi @tritemio -- I'm not sure what the usual Windows behavior is using activate, but on *nix you have to `source activate` to update the `$PATH` as necessary.  On xonsh, you should be able to

```
source-bash activate py2
```

**Comment by krader1961** [comment]
On Mon, Nov 9, 2015 at 4:16 PM, Antonino Ingargiola <
notifications@github.com> wrote:

> On Windows in cmd.exe, Miniconda3 and python 3.4 I start xonsh, activate a
> python 2 enviroment. After that, running python starts python 3.4 (the root
> environment python) instead of python 2:
>
> >xonsh
> temp@laser2002j-PC C:\Data\Antonio\software\src\voltagesensing master $ activate py2
> Activating environment "C:\Users\laser2002j\Miniconda3\envs\py2"...
> temp@laser2002j-PC C:\Data\Antonio\software\src\voltagesensing master $ python
> Python 3.4.3 |Continuum Analytics, Inc.| (default, Nov  7 2015, 13:21:48) [MSC v.1600 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>>
>
>
That's because the anaconda activate command modifies the $PATH environment
variable in a fashion that only works if you're using a bourne-shell
compatible shell; which xonsh is not. I too use anaconda but haven't yet
switched to xonsh as my primary shell so I haven't yet invested the time to
write a wrapper that handles this. But for what it's worth below are the
zsh functions I use.

function con {
    # Activate the named conda environment or the root environment if none
is
    # specified.
    if [[ $# -eq 0 ]]; then
      conda info -e
    else
      source ~/conda/bin/activate ${1:-root}
    fi
}

function coff {
    # Remove all conda environments from our PATH.
    typeset -a _path
    typeset _p
    for _p in $path; do
        if [[ $_p != $HOME/conda/* ]]; then
            _path+=$_p
        fi
    done
    path=($_path)
    unset CONDA_DEFAULT_ENV
}


-- 
Kurtis Rader
Caretaker of the exceptional canines Junior and Hank

**Comment by tritemio** [comment]
@gforsyth on windows you don't source but call the "activate" script like in the previous example. For me the advantage of using xonsh would be not having to install bash on windows.

**Comment by tritemio** [comment]
@krader1961 I'm using cmd.exe on windows, not bash.

**Comment by krader1961** [comment]
On Mon, Nov 9, 2015 at 5:35 PM, Antonino Ingargiola <
notifications@github.com> wrote:

> @krader1961 <https://github.com/krader1961> I'm using cmd.exe on windows,
> not bash.
>

Okay, but that doesn't alter the fact that xonsh is not cmd.exe and has
different conventions. Xonsh assumes that the current environment (e.g.,
$PATH) cannot be modified by a subprocess. I'm guessing that the ms-windows
version of anaconda activate directly mutates the cmd.exe equivalent of
$PATH. That won't work with a shell like bash or xonsh even if you're
running them on ms-windows.

If you're lucky someone on this mailing list has already figured it out and
will notice your query. Otherwise you'll need to examine what the activate
command source code and figure out a xonsh equivalent. It might even be
that the activate command can be invoked in a UNIX like manner (meaning
that it writes to stdout a "PATH=" assignment statement)  in which case
@gforsyth's answer should work.

-- 
Kurtis Rader
Caretaker of the exceptional canines Junior and Hank

**Comment by tritemio** [comment]
Indeed #277, already reported.
