### ISSUE TITLE
Update conda install docs to point to xonsh org

### ISSUE THREAD

**Issue by scopatz** [scopatz/xonsh#554]
Pretty self explanatory.  Also, we should probably upload a prompt-toolkit package, for safety.

**Comment by melund** [comment]
How should we use the xonsh channel on Anaconda.org? 

I think we could configure it, so every merge to master triggers a build that is uploaded to the dev channel. Thus, we can always install the bleeding edge using 

```
conda install -c xonsh/channel/dev xonsh
``` 

When we need to make an official release we can just log in to on anaconda.org and move a version to the main channel. 

I have also added builds of prompt_toolkit and its dependency `wcwidth`. Both are built from my forks on GitHub (where I added the conda build recipes). I have made a pull request (https://github.com/jonathanslenders/python-prompt-toolkit/pull/196) to @jonathanslenders to get the recipe into prompt_toolkit, but it would be great if both packages could be hosted officially by continiuum as @asmeurer suggested. 

The conda packages are versioned from the latest tag in the git tree with a build number which is the number of commits since the last version tag. 

The free build server on anaconda.org is linux only, so the build script is configured to use `conda convert` to convert the build to other platforms. Unfortunatly, there are a number of limitations to `conda convert`.

The biggest limitation is that we can't have different dependcies for different platforms, as we can with native conda builds. Thus, we can't make builds where only windows is dependent on prompt_toolkit. Would it be Ok that the conda packages for Linux also installs prompt_toolkit? 

The setup.py doesn't have to include the dependency so pip and source installs would be unaffected.

**Comment by scopatz** [comment]
> Thus, we can always install the bleeding edge using

I think that is an awesome idea.  

> The biggest limitation is that we can't have different dependcies for different platforms, as we can with native conda builds. Thus, we can't make builds where only windows is dependent on prompt_toolkit. Would it be Ok that the conda packages for Linux also installs prompt_toolkit?

That is a limitation I am willing to accept.  The idea with keeping the hard dependencies to a minimum is that it is very annoying to just "try something out" if you have a long list of requirements.  However, with the conda package, we know we have a fully capable package manager and so it is reasonable to have a "batteries included" package that does require some or all of the optional dependencies.

**Comment by melund** [comment]
> >Thus, we can always install the bleeding edge using

> I think that is an awesome idea.

Great. Then we just need to enable the webhook to you gihub account. You need to authorize that here:
https://anaconda.org/xonsh/xonsh/settings/ci

> That is a limitation I am willing to accept. The idea with keeping the hard dependencies to a minimum is that it is very annoying to just "try something out" if you have a long list of requirements. However, with the conda package, we know we have a fully capable package manager and so it is reasonable to have a "batteries included" package that does require some or all of the optional dependencies.

I have created a pull request for this: https://github.com/scopatz/xonsh/pull/555

**Comment by scopatz** [comment]
> Great. Then we just need to enable the webhook to you gihub account. You need to authorize that here: https://anaconda.org/xonsh/xonsh/settings/ci

Done.

**Comment by scopatz** [comment]
I think that this is now closable, but feel free to reopen @melund
