### ISSUE TITLE
cd into directories with whitespaces (windows)

### ISSUE THREAD

**Issue by melund** [scopatz/xonsh#559]
Prompt toolkit autocompletes this: 
mel@ANYBODY-MEL ~ $ cd 'Applica<tab>

mel@ANYBODY-MEL ~ $ cd 'Application Data\' <enter>
cd takes 0 or 1 arguments, not 2

I haven't noticed this before since I mostly run with `$FORCE_POSIX_PATHS = True`

**Comment by scopatz** [comment]
So it should probably be `\\'`

**Comment by melund** [comment]
Yes, maybe. But it looks really bad. Maybe `$FORCE_POSIX_PATHS = True` should be default on windows.

**Comment by scopatz** [comment]
I think the False default conforms to what most people would expect at first blush.  Then people who know they want posix-paths won't be inconvienced by setting this to True, because it is something they want. Disabling something that you don't want is more frustrating than enabling you do, in my opinion.

**Comment by melund** [comment]
I think this is more or less fixed by now. So I will just close it.
