### ISSUE TITLE
Replace prompt() for ptk with a class

### ISSUE THREAD

**Issue by scopatz** [scopatz/xonsh#579]
This was first brought up in #578 as a way to asynchronously add to history.

**Comment by adqm** [comment]
Also, I'm not sure we need to make our own wrapper class.  Since `prompt` [wraps `CommandLineInterface`](https://github.com/jonathanslenders/python-prompt-toolkit/blob/41f45c90e37e32bebc1d9e143cb192280a3bc569/prompt_toolkit/shortcuts.py#L463-L466), I'm assuming the thing to do would be to make instances of `CommandLineInterface` and `Application` directly, and presumably that would be give us some more control, access to more variables, etc.

**Comment by scopatz** [comment]
Ahh yeah, using CommandLineInterface directly is probably the best option.

**Comment by scopatz** [comment]
This has been done.
