### ISSUE TITLE
xonsh should set the $SHELL environment variable on startup

### ISSUE THREAD

**Issue by riccardomurri** [scopatz/xonsh#623]
The $SHELL variable is not reset upon entering `xonsh`::

        $ echo $SHELL
        /bin/bash

        $ exec xonsh
        $ echo $SHELL
        /bin/bash

Can you please add this feature?

**Comment by scopatz** [comment]
Thanks for reporting @riccardomurri

**Comment by scopatz** [comment]
Actually, this is not something that we should set because it would break UNIX / posix compatibility, see http://tldp.org/LDP/abs/html/internalvariables.html#SHELLVARREF and http://unix.stackexchange.com/questions/45458/why-shell-doesnt-change-when-i-run-new-shell

This password should be changed from `/etc/passwd`.

**Comment by riccardomurri** [comment]
Sorry, I misunderstood `$SHELL` as meaning "the current shell" instead of "the users' login shell". Then Xonsh' behavior is correct as is.
