### ISSUE TITLE
Add setproctitle conda package to xonsh channel

### ISSUE THREAD

**Issue by scopatz** [scopatz/xonsh#656]
Since we now have setproctitle as an optional dependency, it would be nice to have a package for this too, so the xonsh recipe could depend on it.

**Comment by asmeurer** [comment]
Because it's a compiled library you should try to compile it on an older Linux (like CentOS 5) so that it will work everywhere. You probably don't need to worry about this for OS X or Windows.

**Comment by scopatz** [comment]
Well, I was planning on trying to use conda-forge for this, and I think that they do use and old OS. If someone wants to beat me to this, though, I'd be happy :)

**Comment by asmeurer** [comment]
conda-forge should do the trick. Do you build other packages for xonsh there too?

**Comment by scopatz** [comment]
I've built xonsh itself there, and I think prompt-toolkit too at some point.

**Comment by melund** [comment]
I think this is a great idea to include setproctitle in the conda dependencies. Never heard of conda-forge, can it be used for windows packages as well. Prompt-toolkit and xonsh on the anaconda.org are built with Anaconda build server and converted with conda-convert. It has a few downsides though...

**Comment by scopatz** [comment]
Yep, @melund. The point of conda-forge is to be able to build via free CI services packages for Linux, Windows, and Mac.  It is kind of a pain to set up right now, since it is still young, but luckily they have a repo called https://github.com/conda-forge/staged-recipes.  This is already all set up and so all that you need to do is open a PR with a recipe and it will go an build it.  @pelson and @ocefpaf can probably tell you more.

**Comment by asmeurer** [comment]
Another option, if that doesn't pan out, would be to rewrite or extract setproctitle as a pure Python library using ctypes.

**Comment by scopatz** [comment]
Yeah, that is totally another option if someone wants to do that.

**Comment by ocefpaf** [comment]
@scopatz I have setproctitle in ioos.  I will be sending it to conda-forge soon...

**Comment by scopatz** [comment]
@ocefpaf awesome! Thanks!

**Comment by scopatz** [comment]
There is now a conda-forge package (https://anaconda.org/conda-forge/setproctitle) that we should probably copy into the xonsh channel.

**Comment by scopatz** [comment]
Thanks again to @ocefpaf!

**Comment by pelson** [comment]
> There is now a conda-forge package (https://anaconda.org/conda-forge/setproctitle) that we should probably copy into the xonsh channel.

Or just use ```conda-forge``` direct :wink: ?

**Comment by scopatz** [comment]
Ideally, yes, but then the install line on the xonsh docs would need to look like `conda install -c xonsh -c conda-forge xonsh`.  

Is there a way in a recipe to specify channels for required packages?  That would be ideal :)

**Comment by pelson** [comment]
> Is there a way in a recipe to specify channels for required packages? That would be ideal :)

Nope. Unlikely that that will ever happen I'd guess - sounds like a bit of a headache to manage packages like that.

Of course, users can just:

```
conda config --add channels conda-forge
conda install xonsh
```

The xonsh recipe is also built by conda-forge.

**Comment by asmeurer** [comment]
There were a lot of discussions about adding this to conda. It never happened because there were some technical difficulties (conda merges all the channels into one index and assumes everywhere that that index is the same for everything), and also because there were some worries (at least from me) that people would misuse this by specifying required channels when all they really wanted were added channels. My hope for this was and is that features would emerge on anaconda.org that would make it easier for owners of one channel to automatically or semi-automatically pull in packages from another channel. 

Even without those features, I think that is what you should try doing. It's better to have all these packages on the `xonsh` channel itself rather than `conda-forge`. The anaconda command line client has a copy feature that makes it pretty easy (I think you have to use the Python API).

**Comment by pelson** [comment]
>  It's better to have all these packages on the xonsh channel itself rather than conda-forge

Just to clarify, is that because the ```xonsh``` channel would be smaller, and therefore help the ```conda``` solver, or simply a control thing?

**Comment by asmeurer** [comment]
No I mean just so that users only have to write `-c xonsh` to get everything.

**Comment by pelson** [comment]
> No I mean just so that users only have to write -c xonsh to get everything. 

Right, but everything is already on ```conda-forge``` as per https://github.com/conda-forge/staged-recipes/tree/master/recipes. I'm happy either way, but just want to understand any concerns/preferences with ```conda-forge``` (you guys are trailblazing here).

**Comment by asmeurer** [comment]
I guess it's up to Anthony. If everything is on conda-forge, then the installation could just be `-c conda-forge` instead of `-c xonsh`. It's just as simple, though I guess it's less "branded". The other downside is that that way *every* new package that we want to give to users has to be added to conda-forge (but that's maybe what we want to do anyway). 

Then again, writing a script that uses the Anaconda API to copy everything to the xonsh channel won't be difficult.

**Comment by scopatz** [comment]
Well, I don't think it is just up to me :). @melund has done most of the work with conda / xonsh (including the awesome ability to install dev packages). I would say that it is sort of his call, if anyone's.  But my suspicion is that the dev package thing would be harder if everyone who wanted to set it up had to go through the conda-forge channel rather than their package specific channel.  This is why I think copying packages from conda-forge could ultimately be less of a headache overall.  In any event, I'll happily defer to @melund if he wants to make a decision.

As per trailblazing, I also believe that you all, @pelson, @ocefpaf, et al., are the ones conda-forging ahead :)  I'm just trying to keep up!

**Comment by asmeurer** [comment]
Does conda-forge make it easy to run some "anaconda copy" script after the "anaconda upload"?

**Comment by melund** [comment]
Like @scopatz I am mostly for keeping the xonsh channel on anaconda.org. At least for now. I do see a great potential with conda-forge, espicially if we can rid of conda-convert and build natively on all platforms.

I don't think it should be a big deal to copy the necessary packages to the xonsh channel. As @asmeurer suggest it may be possible to script it. `Anconda copy` has been broken for quite a while, but it seems to have been fixed a few weeks ago https://github.com/Anaconda-Server/docs.anaconda.org/issues/119

**Comment by asmeurer** [comment]
I don't know about the command line but I used it from the Python API a while back and it worked great.

**Comment by melund** [comment]
I don't know if there were any difference. I think that copying was disabled server side. I used the command line to copy packages before, but it has been out of function since October.

**Comment by asmeurer** [comment]
Oh I did it before October.

**Comment by asmeurer** [comment]
Even if copying doesn't work, you can always just upload the file twice. Copying is only an optimization for anaconda.org itself.

**Comment by melund** [comment]
Yes. But the point is that it was finally fixed two weeks ago :)

**Comment by melund** [comment]
Ohh. Do you have any examples of using the API instead of the command line?

**Comment by ocefpaf** [comment]
I did not know that `Anconda copy` was fixed nor that there was a Python API.  That is interesting.

I am using a different approach (created by @pelson) to share the recipe rather than the final binary. (See [here](https://github.com/ioos/conda-recipes/pull/554/files) for an example).

Sharing recipes have its advantages (like allowing for build customization and/or build matrix different from the recipe place original) and disadvantages (increase CI build time). 

Is `xonsh` built using CIs like conda-forge? If so maybe that is another option.

**Comment by asmeurer** [comment]
No, and I don't think it's documented either (unless that's changed). I generally `import binstar` (or is it `import anaconda` now?) and play with it interactively until I figure it out.

**Comment by melund** [comment]
Xonsh is just build using [anaconda build](http://docs.anaconda.org/build.html). It allows for free builds on Linux. After the build we use conda-convert to convert the conda package to windows and mac. 

You can see the CI config here:
``` 
package: xonsh

platform: 
 - linux-64

engine:
 - python=3.5
 - python=3.4


script:
  - conda build recipe

after_success:
   - conda convert -p all /opt/miniconda/conda-bld/linux-64/xonsh-*.tar.bz2 -o /opt/miniconda/conda-bld

after_failure:
   - echo "Build failed!"

build_targets:
   - /opt/miniconda/conda-bld/*/*.tar.bz2
```

**Comment by scopatz** [comment]
For reference, I just copied setprotitle with the following command. It was trivial.

```console
scopatz@localhost ~ $ anaconda copy --to-owner xonsh conda-forge/setproctitle/1.1.9
Using Anaconda Cloud api site https://api.anaconda.org
Copied file: linux-64/setproctitle-1.1.9-py34_0.tar.bz2
Copied file: win-32/setproctitle-1.1.9-py27_0.tar.bz2
Copied file: linux-64/setproctitle-1.1.9-py35_0.tar.bz2
Copied file: linux-64/setproctitle-1.1.9-py27_0.tar.bz2
Copied file: osx-64/setproctitle-1.1.9-py34_0.tar.bz2
Copied file: osx-64/setproctitle-1.1.9-py27_0.tar.bz2
Copied file: osx-64/setproctitle-1.1.9-py35_0.tar.bz2
Copied file: win-32/setproctitle-1.1.9-py34_0.tar.bz2
Copied file: win-32/setproctitle-1.1.9-py35_0.tar.bz2
Copied file: win-64/setproctitle-1.1.9-py27_0.tar.bz2
Copied file: win-64/setproctitle-1.1.9-py34_0.tar.bz2
Copied file: win-64/setproctitle-1.1.9-py35_0.tar.bz2
Copied 12 files
```

**Comment by pelson** [comment]
> Does conda-forge make it easy to run some "anaconda copy" script after the "anaconda upload"? 

Yeah, I've been considering this for @ocefpaf too. Essentially, that would allow conda-forge to do the grunt, and other channels to pick off the bits that they actually care about. First though, we need to get on and finish conda-forge proper so that anybody can use it (actually, far less work that it might appear).

@scopatz / @melund - anaconda build looks good, but the fact that you only get Linux builds for free puts it against CI services like TravisCI and CircleCI, and TBH, it can't compete. @asmeurer is clearly going to be able to give more insight, but I personally don't use ``conda convert`` - the only way that you can be *certain* a package works on a particular platform is to test it on that platform. That is why conda-forge builds on the target platform rather than doing any conversions.

Back to the original discussion - I think it is awesome that you guys thought of using conda-forge for the building, and if you decide to copy the built distributions into the xonsh channel, that is cool too.

**Comment by asmeurer** [comment]
Yeah, conda convert works if everything is pure Python and you know that everything is the same on all platforms. If you are building other people's packages, you don't necessarily know this without checking (one way conda convert can fail is if a package has code in setup.py that does something different on Windows for example). Building on all platforms is better. It doesn't break down as soon as you want to add something platform specific or do something that isn't pure Python (or maybe isn't Python at all). The only reason anyone cares about conda convert is that it's not so easy to have access to a usable build environment for OS X, Linux, and Windows , so it's a workaround for a large chunk of packages which technically can be "built" on any platform and translated.  

And since I don't work for Continuum any more, I guess I can come out and say that I completely agree with your assessment of anaconda build. conda-forge is a much better way to do it. I really hope that it takes off.

**Comment by ocefpaf** [comment]
> I really hope that it takes off.

+:100: 

@pelson we just talked about this and I missed the opportunity to ask.  I do want to send more packages to the conda-forge channel, but  issue about `feedstocks` versus `staged_recipes` is still a blur to me.  I see clear advantages of `feedstocks` for packages like `geos`, but little advantages for packages like `setproctitle`. Basically the C-dependencies and long build time versus pure python stuff.

I know that you are working on a way to create `feedstocks` from the recipe on `staged_recipes`. So... The question is: Should I start populating `staged_recipes` with the most popular packages in the IOOS channel?  I am OK to start doing that and start promoting the use of `conda-forge` as an alternative/complement to IOOS.

(@scopatz apologizes for hijacking the original topic of this thread :grimacing:)

**Comment by scopatz** [comment]
@ocefpaf hijack away! I am enjoying the discussion.

The distinction is a blur to me too.  Though, persoanlly if you measure it in terms of effort or pain, I think that `staged-recipes` is currently the clear winner. While being able to make your own feedstocks is nice if you want total control of the repo and everything, that control comes at a pretty steep learning curve, in my opinion.

**Comment by scopatz** [comment]
The original task here has been completed. Feel free to continue using this thread for discussion.

**Comment by pelson** [comment]
> The original task here has been completed. Feel free to continue using this thread for discussion.

Maybe https://github.com/conda-forge/staged-recipes/pull/50 is a good place for the staged-recipes vs feedstock conversation :wink:
