### ISSUE TITLE
Custom Prompt

### ISSUE THREAD

**Issue by arkhan** [scopatz/xonsh#674]
Hello, I have a question as I can get a prompt like the one shown in the picture ..?

![Imgur](http://i.imgur.com/ogOeqyy.png)

Thanks, Great work

**Comment by scopatz** [comment]
Hi @arkhan, do you just mean a blue arrow?

**Comment by scopatz** [comment]
Sorry the image is a little hard to understand, but I'd like to help!

**Comment by arkhan** [comment]
Hello, in zsh I have this configuration

PROMPT=' %{$fg_bold[blue]%}%(!,%{$fg_bold[red]%}>%{$reset_color%},>) %{$reset_color%}'
RPROMPT='$(git_super_status) %{$fg_bold[black]%}%~%{$reset_color%}'

PROMPT result in the blue arrow, and
RPROMPT result in working path like short_cwd,

as I can get the same thing in xonsh....?

**Comment by melund** [comment]
I don't think we have support for a right justified prompt and I don't know if prompt-toolkit supports it. I guess readline probably does.  But it would be a nice feature. Having the prompt span two lines is possible

**Comment by scopatz** [comment]
Very interesting. I don't believe that there is any readline magic that will give a right prompt, looking at the readline docs: https://cnswww.cns.cwru.edu/php/chet/readline/readline.html

There might be some trick in unicode that can be played.  zsh is probably using some curses or vt1000 compatible feature that wouldn't be available everywhere.

I don't think that ptk supports this, but it is worth asking for.

Otherwise, it seems like there is a justification for an urwid / curses based shell, which is something that I have been thinking about for some time (ie from the first xonsh commit).

**Comment by scopatz** [comment]
Please see jonathanslenders/python-prompt-toolkit#237

**Comment by arkhan** [comment]
+1

**Comment by scopatz** [comment]
@arkhan, #696 and the master branch of prompt-toolkit should be capable of implementing what you want. Can you give them a try, please?

**Comment by arkhan** [comment]
work fine..

**Comment by offero** [comment]
Now that these issues are closed, is there any guidance on how to achieve this?

**Comment by gforsyth** [comment]
http://xon.sh/tutorial.html#customizing-the-prompt

You want to set the env var `$RPROMPT`
