### ISSUE TITLE
Regex globbing is misleading

### ISSUE THREAD

**Issue by BlaXpirit** [scopatz/xonsh#711]
Filename expansion using regular expressions is pinned to the beginning of the filename, but not to the end. Some examples:

```console
$ ls
abac
$ `a.*a`
['abac']
$ `b.*c`
[]
$ `a`
['abac']
$ `b`
[]
$ `bac$`
[]
$ `.*bac$`
['abac']
```

I think that such arbitrary behavior is very inconvenient or even dangerous.

I know that under the hood this is caused by my arch-nemesis, [`re.match`](https://docs.python.org/dev/library/re.html#re.match). Please either pin both the beginning and the end of the string (as if the regex is `^regex$`, and to search anywhere in the filename you'd need to use `.*regex.*`), or, much better, just get rid of the pinning and use [`re.search`](https://docs.python.org/dev/library/re.html#re.search).

**Comment by gforsyth** [comment]
Hey @BlaXpirit , this seems reasonable to me and I've put in a PR to address it.  Behavior is

```
$ ls
abac
$ `a.*a`
['abac']
$ `b.*c`
['abac']
$ `a`
['abac']
$ `b`
['abac']
$ `bac$`
['abac']
$ `.*bac$`
['abac']
```

**Comment by BlaXpirit** [comment]
Now I see that [`re.fullmatch`](https://docs.python.org/dev/library/re.html#re.fullmatch) implements the `^regex$` behavior; I prefer this one.

**Comment by gforsyth** [comment]
Hey @BlaXpirit -- I _think_ that should be ok, but I need to think about it a little more and test to make sure it doesn't screw with things like path completion.

**Comment by BlaXpirit** [comment]
In regards to breaking the API (as mentioned in the PR):

I'm sure that more people "rely" on the behavior to be that of `re.fullmatch` than what it actually is and are already being bitten by it. Nobody would just expect such arbitrary behavior, especially if it is not mentioned in documentation.

**Comment by scopatz** [comment]
Well, my question to you @BlaXpirit is whether you would mind having to set a `$XONSH_REGEX_GLOBBER` or similar environment variable in your xonshrc in order to get whatever behaviour you wanted?  I think this is probably the best solution because I can see use cases for all of these functions.

**Comment by BlaXpirit** [comment]
Well sure, that would be the smallest step towards resolving this. But I don't see why the default would be having to write `regex$` for a full match and `.*regex` for a search, a behavior that isn't used by any major regex-related tool.

I can't stress this enough, many people *will* assume this to be a full-match search just because running into a counter-example (before it's too late and e.g. `rm` receives unexpected arguments) is not a likely event

**Comment by BlaXpirit** [comment]
Oh, and changing the behavior of xonsh sctipts based on a config file would obviously compromise their portability.

**Comment by scopatz** [comment]
Hi @BlaXpirit, I respect that this is something that is a pain point for you and I want to address that. But also, this is the first report that we've had that this could be a pain point for anyone.  Now that coule be because xonsh is new, people know what to expect from match, or any number of other reasons. So, yes, you are totally right that some people will assume `fullmatch()` behaviour. However, I wrote this originally in the way that I did (not saying that is correct) because I would have assumed `match()` behaviour, which is sort of the default for the `re` module in my opinion.

The main problem is that changing from match in any way has the potential to break existing scripts.  changing to `fullmatch()` has the least likelihood of doing damage. Changing to `search()` could really mess things up.

Now, that said, maybe it is best to rip the band-aid off sooner rather than later if we are convinced that there is a better way for everyone (like with color management).

However, this seems to me to be the sort of thing that is really a matter of opinion and assumptions, like what was said above.  In this case, there may be many choices but no clear winner.  Therefore, the winner should either be stability or customizability. 

You are totally right that this could cause problems if users set the environment variable and then a script they run expects another.  To that end, I think that your point on documentation is a very good one. I'll also note that the script could set this variable themselves, either in a small context (using `xonsh.tools.swap()` or similar) or globally.  This is true for a number of other customizations we have.  

So personally, I feel that addling an environment variable is the safest and most useful option. If you agree, let us know and we can get it coded up or put in a PR. We love to have new contributors :).

**Comment by adqm** [comment]
I missed this conversation earlier, but I would also be in favor of switching to fullmatch, largely for the same reasons @BlaXpirit mentioned above (other tools that use regex on the command line tend to work this way, closer match to the globbing syntax, etc).

I think I agree most people's expected behavior for `` `a` `` is that it will only match filenames that are exactly "a", not those that start with "a".  To me, that feels more natural, and `` `a.*` `` would match filenames that start with "a".

I'm of the opinion that the best time to break backward-compatibility is when the project is young, so I would be in favor of this change happening now.  Or this could be something that we put into 0.3 if you think that's the right time.  But if we're taking votes, I vote in favor of this change.

**Comment by scopatz** [comment]
I am happiest with `fullmatch()`.

**Comment by scopatz** [comment]
Thanks to @adqm, `fullmatch()` has now been merged in.  Feel free to close @BlaXpirit.

**Comment by BlaXpirit** [comment]
Great, thanks!
