### ISSUE TITLE
Capturing output of `locate` on OS X slows down the process significantly

### ISSUE THREAD

**Issue by azag0** [scopatz/xonsh#832]
See below. In fish, it works alright. Could this be some sort of caching going or not going on on the side of locate? But then again, locate is all about cache by default, so I don't really see what could be going on there.
```
🐌 12:09 her@air ~ time locate '*keybase*' | wc -l
        4.26 real         4.20 user         0.04 sys
    8480
🐌 12:10 her@air ~ t = time(); print(len($(locate '*keybase*').split('\n'))); time()-t
^C
467
15.955388069152832
🐌 12:10 her@air ~ t = time(); $[locate '*keybase*' | wc -l]; time()-t
    8480
4.329284906387329
🐌 12:24 her@air ~ time fish -c 'for f in (locate "*keybase*"); echo $f; end | wc -l'
    8480
        4.99 real         4.83 user         0.15 sys
```

**Comment by scopatz** [comment]
Hi @azag0, thanks for reporting! And sorry for taking so long to get back to you...

I can reproduce this on Linux with "*cmake*" instead of keybase.  I think that this is a simple matter of overfilling a buffer.  I notice that if I interrupt it after it starts to hang, 

```console
scopatz@artemis ~ $ x = $(locate "*cmake*")
^C
scopatz@artemis ~ $ len(x)
65536
```

Then the length is ~65 kb, but more importantly it is exactly `2**16`. This makes me think that we are not clearing the file buffer fast enough. This also explains why it works just fine for me for output less than 65 kb. 

Obviously this limit is non-ideal and should be fixed.

**Comment by adqm** [comment]
@scopatz, does this still happen to you even after #875 was merged in?  I can't reproduce this since that change.

**Comment by scopatz** [comment]
Hah! That fixed it @adqm! Thanks for pointing that out. It seems to work now. I hadn't reinstalled xonsh on my desktop since last week.  (I was traveling this weekend, and so was working from my laptop.)  @azag0, can you please confim that this works for you now and then potentially close this issue? Thanks!

**Comment by adqm** [comment]
Great!  Yep; this problem (which was nagging me on some work-related stuff) was why I implemented that change :)

**Comment by scopatz** [comment]
Always the best motivator!

**Comment by azag0** [comment]
Perfect! Works for me now. Thanks.
```
🐌 17:14 ~ time locate "*test*" | wc -l
        3.22 real         3.15 user         0.04 sys
  497256
🐌 17:14 ~ t = time(); print(len($(locate '*test*').split('\n'))); time()-t
497257
8.449526071548462
```
Wonder whether the slowdown comes from `string.split` or Xonsh middleware.

**Comment by azag0** [comment]
I guess `wc` is crunching the output asynchronously, so that's probably why.
