### ISSUE TITLE
Wrong error reporting while piping

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [scopatz/xonsh#844]
Hello I was trying out the shell and I remarked a strange thing:

```
$ which xonsh > /etc/shells
xonsh: /etc/shells: no such file or directory
$ ls -lah /etc/shells 
-rw-r--r-- 1 root root 116 mars  28 23:13 /etc/shells
```

I think the error should be: "Permission denied" instead of "file not found".

By the way it does not work event with sudo but it seems to be normal since bash has the same behavior. Do you know how to pipe to a write protected file ?

**Comment by adqm** [comment]
You are right about the error reporting.  We can certainly improve on that.

As for sending that result to `/etc/shells`, the problem is that `sudo` only runs the command as root, not the act of sending the output to the file (hence the permission error).

To work around, one could either:

* Become root by running `sudo su` and then run `which xonsh >> /etc/shells`
* Manually edit `/etc/shells` as root to add a line at the bottom containing the absolute path to xonsh.

FWIW, I also think you want `>>` instead of `>` (append the new line to the end of the file, rather than rewriting everything) unless you're _really_ going all in with xonsh :)

**Comment by GuillaumeLeclerc** [comment]
I thought there would be a simpler way to do this with sudo. I don't want to sudo su because root has bash as a default shell (I keep it if xonsh break). I just used vim and and it worked perfectly. I just made this issue to improve the error message

**Comment by scopatz** [comment]
Hi @GuillaumeLeclerc - I believe that this has been addressed.  Would you mind closing this, please?

**Comment by scopatz** [comment]
If you feel comfortable with the new version that is!

**Comment by GuillaumeLeclerc** [comment]
It's perfect. Thank you !
