### ISSUE TITLE
Impossible to run a bash command inside a alias

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [scopatz/xonsh#852]
Hello,

I have this alias:

```
aliases['fif'] = lambda x, y: $("echo how are you " + x[0])
```

and when I use it I get:

```
xonsh: subprocess mode: permission denied: fif
```

Is it normal or I am making something wrong ?

**Comment by tuanhtrng** [comment]
I don't think you can use 'return' in lambda. Check it [here](http://www.secnetix.de/olli/Python/lambda_functions.hawk).

**Comment by GuillaumeLeclerc** [comment]
I edited my issue. The bug(?) is still there. I used a lambda to make it shorter but in my original script I was using a normal python function

**Comment by adqm** [comment]
This is actually just an issue with the way that command is being formed.  Right now, because everything is enclosed in a string, `"echo how are you " + x[0]` will all be treated as a single command (rather than `echo` + some args), and, because that command doesn't exist, things are failing.  That error message could use some work; we'll try to see what we can do about that.

But in order to get this to work, you probably want:
`aliases['fif'] = lambda x, y: $(echo how are you @(x[0]))`

The `$(...)` operator drops down to subprocess mode (no need for quoting there), and then, within subproc mode, the `@(...)` operator is used to inject a Python value.

**Comment by GuillaumeLeclerc** [comment]
That's perfect thanks ! I still have to wrap my head around the context switch
