### ISSUE TITLE
Syntactic Improvements

### ISSUE THREAD

**Issue by scopatz** [scopatz/xonsh#86]
See this reddit thread: http://www.reddit.com/r/Python/comments/2z8hl1/xonsh_a_pythonish_bashcompatible_shell_language/cpgxelz

Basically the idea is to have non-modal syntax (${} means to look things up in the env in Python-mode and it means to compute something in Python when in subprocess-mode.)  One of these should get a different syntax.

The other idea is to convert the contents of the ${} expression to a string automatically in subprocess mode.  This would enable the following:

```console
echo ${3 + 4}
```

**Comment by wrywerytwreywery** [comment]
I like this idea.  The syntax didn't bother me, since I viewed `${...}` as sort of the "run this in the other mode" syntax, but I can see how it would be confusing.

My suggestion would be to leave `${...}` as environment lookup in Python mode, and come up with a different syntax for executing Python in subprocess mode.  I feel like the new syntax probably shouldn't use `$`, since that is (I think) pretty strongly tied to the shell, and it seems like we want something that is tied to Python instead.  So my feeling would be something like `py(...)`, though that would have its own problems.

Converting those outputs into strings does make good sense, I think.

**Comment by scopatz** [comment]
> I feel like the new syntax probably shouldn't use $,

I completely agree.  

> something like py(...), though that would have its own problems.

I really like the idea of using parentheses here because they 'capture' and then return the expression inside of them.  When I was thinking about it this morning, I came up with `!()` as the syntax.  `!` has a connotation of execution and is definitely different than `$`.  `|()` could mean 'pipe to python', but I could see that getting super confusing if you are using a lot of pipes on the same line.  

I am open to suggestions here, but I kinda like `!()` and if I had to choose today that would be it.

> Converting those outputs into strings does make good sense, I think.

Sounds good!

**Comment by wrywerytwreywery** [comment]
I kind of like the `!(...)` syntax.

```
for i in range(500):
    $[touch !("file%03d" % i)]
```

My only (slight) reservation is that `!` means something different in BASH-land, and exploring the history using `!` might be something that xonsh should have in the longer-term.

Something that bash doesn't use (at least to my knowledge) is `@`.  It is arguably uglier (and loses the execution connotation), but I could swear I have seen this character used in some string templating languages, so it might not be too bad for denoting "compute a string and fill it in here":

```
for i in range(500):
    $[touch @("file%03d" % i)]
```

But I could go either way on that.  

FWIW, I do think the pipe syntax would be too confusing.

**Comment by scopatz** [comment]
Luckily, the bash `!` and `!!` syntax doesn't overlap with the `!()` syntax.

**Comment by wrywerytwreywery** [comment]
That's true; my only concern is whether the `!` character itself might associate more strongly with history than with execution.  Also, I think it might be confusing, if that kind of history is implemented at some point, that, for example, `!-2` and `!(-2)` would do different things.  It might not be worth worrying about, but that's why I have a slight preference for `@`, since I don't think `@` means anything on its own in bash (I think only `$@` has meaning).

**Comment by wrywerytwreywery** [comment]
@scopatz, I just submitted a PR to convert the result of `${...}` expressions to strings.  I also have a changeset on my local repo that changes the syntax as we discussed, and I can submit a PR for that, too if you'd like.  I currently have the syntax as `@(...)` in that copy (as that's still the winner in my mind), but I can change it to `!(...)` if that's what you want to go with.

**Comment by wrywerytwreywery** [comment]
`!` also means "not" to me, so maybe that's what I'm sensitive to...

**Comment by scopatz** [comment]
Yeah, I thought about that. It also means factorial to me :) Clearly there are not enough keys on the keyboard....

**Comment by scopatz** [comment]
I think that this has been completed with #113.  Thanks again @wrywerytwreywery!
