### ISSUE TITLE
More variables for prompt

### ISSUE THREAD

**Issue by dimaqq** [scopatz/xonsh#87]
At the very least, most basic bash parity:

* host (an actual hostname as opposed to domain name or fqdn)
* basename of cwd (i.e. last element of cwd)

**Comment by mbollmann** [comment]
I can try to put this in. Do you have any further suggestions of variables that would be nice to have?

With an increasing number of variables, I wonder if we should do `if '{varname}' in prompt: ...` before computing them, instead of just computing them all and passing them to `.format()`.

**Comment by scopatz** [comment]
> I can try to put this in. Do you have any further suggestions of variables that would be nice to have?

Awesome, thanks!  I don't have any suggestions, myself...

> With an increasing number of variables, I wonder if we should do if '{varname}' in prompt: ... before computing them, instead of just computing them all and passing them to .format().

Probably.  Though the colors should probably always be added, rather than checking all the colors.

**Comment by mbollmann** [comment]
@dimaqq, can you clarify what you mean by "an actual hostname as opposed to domain name or fqdn"? The current `{hostname}` variable should return the "actual hostname", shouldn't it?

**Comment by scopatz** [comment]
@mbollmann - that is what I thought!

**Comment by mbollmann** [comment]
Most shells seem to have different variables for "full hostname" and "hostname up to the first dot", but I can't get `socket` to return anything containing a dot on any of my machines (though that might be configuration-dependant!), and I'm not sure if this is what @dimaqq meant.

But I have some other stuff that I added already. Refactoring the formatting so that the variables are only computed when they're used is trickier than I thought, but I hope to have sth. ready soon.

**Comment by scopatz** [comment]
sweet, thanks @mbollmann

**Comment by abadger** [comment]
@mbollmann Regarding making it so that variables are only computed when used, I have something that might provide a framework for that:

https://github.com/abadger/xonsh/commit/22e61899cfd2d13dfa5531f5ef6a739807d751eb

I was waiting to PR that until I heard if it was a desirable direction on the mailing list but I can put it up for review sooner if that helps.

It currently separates "variable only needs to be determined once" and "variable needs to be determined each time the prompt is formatted".  In my implementation the variables that are determined each time the prompt is formatted are only computed if the variable is accessed.  So those do what you want and are not computed if the prompt does not make use of them.

It would be nice to implement the same thing for the static strings although it may not be a huge win: after all, they are only computed once, not every time the prompt is displayed.

**Comment by dimaqq** [comment]
@mbollmann about names

Consider, for example, "irc.cs.hut.fi"

"irc" is hostname, sometimes called short name
"irc.cs" is domain name (assuming certain network settings)
"irc.cs.hut.fi" is fully-qualified domain name

Linux commands for these are "hostname -s/--short", "hostname" and "hostname -f/--fqdn".

If you use the last, note that it may require a DNS query and therefore can break, take time, returned string can change as device migrates between networks, etc...

**Comment by abadger** [comment]
Updated my branch and made a pull request for it.  #125 should implement the optimizations and new prompt variables requested here.  There are a few other things I'm interested in but I'm not yet sure how best to implement them so I'll push them in separate PRs:

* zsh's %y: The tty the user is logged in from (ex: "pts/3" "tty4").  I can do this by calling out to /usr/bin/tty but I don't know if there's a better way.
* A final char that is responsive to the user's privilege level (root vs normal) and the exit status of the last command.  Currently I have my prompt ending with (#|$) and it is highlighted red if the last command exited with an error code.

**Comment by mbollmann** [comment]
@abadger: Using a class for the prompt arguments is what I was doing as well, but it looks like you beat me to it. Yours looks way more sophisticated than what I would've suggested, though, but that might be a good thing with extensibility in mind.

By the way, I would also suggest a `time` variable that returns `datetime.datetime.now()`. The beauty is that you can already format it any way you like in the prompt string via strftime() syntax, e.g. `{time:%H:%M}` etc.

@dimaqq: Thanks for the clarification! I'm still not sure what your request is, though. I understood you as requesting a "host" variable that returns the hostname/short name. But on all machines that I've tried it on, this is what `{hostname}` in the prompt string already returns. Does it return something else for you?

**Comment by dimaqq** [comment]
I get fqdn; granted I have to check why that happens. I suppose it depends on what hostname is being set by dhcp. I'll check that later.

The request is to have separate short host name and host name options; those are different quite often.

**Comment by abadger** [comment]
@mbollmann, nice, I didn't realize that you could use python formatting like that!  I'll add that.  If you have ideas for simplifying I could see if they could still allow for the extensibility I was looking for.  I think that static strings and call-every-time functions are about the right level of complexity but I'm not completely satisfied with the call-once functions.  Maybe I should get rid of the Sentinel and change ```__getitem__``` to be something like:
```
if callable(value):
    if key in self.call_every:
        return value()
    value = value()
    self[key] = value
return value
```
Then for writing a custom Formatter you just add the (key, value) to self and add the key to self.call_every if you want it to be called everytime a prompt is printed.

@dimaqq, I too get fqdn from  socket.gethostname().  The PR should allow you to get just host from using ```{short_host}```

**Comment by abadger** [comment]
PR updated as per my previous comment.

**Comment by scopatz** [comment]
I believe that this has now been addressed.  Please re-open in I am incorrect.
