### ISSUE TITLE
$(which echo) not returning captured output

### ISSUE THREAD

**Issue by JohnLunzer** [scopatz/xonsh#938]
Running ```a = $(which echo)``` will result in ```a``` holding an empty string. But it will print the location of the echo command to the screen.

If I run ```a = $(echo $HOME)``` will result in ```a``` holding the path to the home directory.

I just ran ```conda install -c xonsh/channel/dev xonsh``` to make sure I was updated to most recent.

**Comment by gforsyth** [comment]
Hey @JohnLunzer -- I can't reproduce this on master -- it may be that the conda package is in need of updating.

**Comment by JohnLunzer** [comment]
Oh I saw that there were many changes to which recently, I had assumed xonsh/channel/dev on conda and git master were automatically linked and thought I was safe. I'll check out the master and see what's up.

**Comment by scopatz** [comment]
They used to be, until anaconda.org stopped working.  We can try to reenable it though.

**Comment by melund** [comment]
I think is does work ... have you try installing from the development channel?
`conda install -c xonsh/channel/dev xonsh `

**Comment by GuillaumeLeclerc** [comment]
It works fine for me on a slightly ahead branch.

**Comment by JohnLunzer** [comment]
@melund, as I said I am at the most recent ```conda install -c xonsh/channel/dev xonsh```. I plan on checking out the git master soon.

**Comment by scopatz** [comment]
@JohnLunzer - we also plan on doing a release tomorrow too!

**Comment by melund** [comment]
@JohnLunzer .. Sorry. I didn't see that. But my points is that  `-c xonsh/channel/dev` does have the newest master. The lastes was build just 17 min ago as I write. https://anaconda.org/xonsh/xonsh/builds

```
C:\Users\mel>conda install -c xonsh/channel/dev xonsh
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ........
Solving package specifications: .........

Package plan for installation in environment C:\Users\mel\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    xonsh-0.2.7                |         py35_527         473 KB

The following packages will be UPDATED:

    xonsh: 0.2.7-py35_246 --> 0.2.7-py35_527

Proceed ([y]/n)?
```
The build number `527` is the number of commits it is ahead of version 0.2.7.

**Comment by scopatz** [comment]
Whoops! Sorry for misleading you @JohnLunzer!

**Comment by JohnLunzer** [comment]
@melund, there is no way the conda channel is synced with the master, because I've been been running ```conda install -c xonsh/channel/dev xonsh``` since yesterday morning and it's been at ```0.2.7-py35_527``` the entire time. There have been numerous commits since then.

**Comment by melund** [comment]
Ahh. Something happened yesterday. ( https://anaconda.org/xonsh/xonsh/files ) Where anaconda.org suddenly started to fail to get the git revisions during the build. So every build since then has just gotten revision 0.0.0. 

I tried to recreate the way Anaconda checks out the repo:
```
$ git clone --recursive --depth=50 --branch=master https://github.com/scopatz/xonsh.git
...
$ git checkout --quiet ec2298a1bdf676a
```
Then if I run:
```
$ git describe --tags --dirty
fatal: No names found, cannot describe anything.
```
I also get an error here, so that explains the missing revisions. It can't find the tags in the shallow clone. It should have returned the `0.2.7` tag and the number of commits since. 

I think it is because Anaconda.org uses a shallow clone with depth 50. I think 50 refers to the number of first parent commits. So I think that we yesterday passed 50 pull request to master since the last release ;) 

I don't think I can configure the depth of the clone, so I can't do anything about it now.

I guess we should just release more often. It is a good day for a `0.3`release

**Comment by JohnLunzer** [comment]
Perhaps a separate issue should be created for the conda sync issue. 

This issue can likely be closed as now that I am on the git master branch the issue is fixed.
